// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/18/2025, 8:19:36 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/thier/projet_config-nhost-simple/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projet_config-nhost-simple/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projet_config-nhost-simple/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projet_config-nhost-simple/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projet_config-nhost-simple/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projet_config-nhost-simple/plugins/**/*.{js,ts,mjs}","/home/thier/projet_config-nhost-simple/composables/**/*.{js,ts,mjs}","/home/thier/projet_config-nhost-simple/utils/**/*.{js,ts,mjs}","/home/thier/projet_config-nhost-simple/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projet_config-nhost-simple/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projet_config-nhost-simple/app.config.{js,ts,mjs}","/home/thier/projet_config-nhost-simple/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;